# Generated by Django 4.2.9 on 2024-04-09 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tlist",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tlist",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_lists", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="tlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="Lists.tlist",
            ),
        ),
    ]
