# Generated by Django 4.2.7 on 2024-01-26 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tlist",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_lists", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
