# Generated by Django 4.2.9 on 2024-01-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lists", "0003_rename_title_tlist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tlist",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
