# Generated by Django 4.2.9 on 2024-04-19 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Lists", "0003_remove_tlist_city_remove_tlist_likes_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="tlist", name="likes_count",),
        migrations.AddField(
            model_name="tlist",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_lists", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
