# Generated by Django 4.2.9 on 2024-02-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lists", "0004_tlist_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tlist",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
