# Generated by Django 4.2.9 on 2024-02-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Lists", "0005_tlist_is_public"),
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tlist",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Users.customuser"
            ),
        ),
        migrations.AlterField(
            model_name="tlist",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_lists", to="Users.customuser"
            ),
        ),
    ]
